import { createHash } from 'node:crypto';
import type { ReportExportFormat, ReportExportResult, ReportSnapshot } from './types';

function checksum(payload: string) {
  return createHash('sha256').update(payload).digest('hex');
}

function csvCell(value: unknown): string {
  const text = typeof value === 'string' ? value : JSON.stringify(value ?? '');
  return `"${text.replaceAll('"', '""')}"`;
}

export function exportSnapshotAsCsv(snapshot: ReportSnapshot): ReportExportResult {
  const rows = [
    ['Report ID', snapshot.metadata.report_id],
    ['Report title', snapshot.metadata.report_title],
    ['Report type', snapshot.metadata.report_type],
    ['Period start', snapshot.metadata.period_start],
    ['Period end', snapshot.metadata.period_end],
    ['Financial year', snapshot.metadata.financial_year ?? ''],
    ['Basis', snapshot.metadata.basis],
    ['Status', snapshot.metadata.status],
    ['Version', snapshot.metadata.version],
    ['Generated at', snapshot.metadata.generated_at],
    [],
    ['Validation severity', 'Rule', 'Title', 'Message'],
    ...snapshot.validation.map((item) => [item.severity, item.rule, item.title, item.message]),
    [],
    ['Payload JSON'],
    [JSON.stringify(snapshot.data)],
  ];
  const payload = rows.map((row) => row.map(csvCell).join(',')).join('\n');
  return {
    reportId: snapshot.metadata.report_id,
    format: 'csv',
    fileName: `${snapshot.metadata.report_type}-v${snapshot.metadata.version}.csv`,
    contentType: 'text/csv; charset=utf-8',
    payload,
    checksumSha256: checksum(payload),
  };
}

export function exportSnapshotPlaceholder(snapshot: ReportSnapshot, format: Exclude<ReportExportFormat, 'csv'>): ReportExportResult {
  const payload = JSON.stringify({
    metadata: snapshot.metadata,
    validation: snapshot.validation,
    message: `${format.toUpperCase()} export is generated by the document-production renderer and stored in private document export storage.`,
    templates: [
      'report-cover',
      'report-contents',
      'statement-page',
      'notes-page',
      'appendix-page',
      'signature-approval-page',
      'evidence-index',
      'export-footer',
    ],
  }, null, 2);
  const extension = format === 'excel' ? 'xlsx' : format;
  return {
    reportId: snapshot.metadata.report_id,
    format,
    fileName: `${snapshot.metadata.report_type}-v${snapshot.metadata.version}.${extension}`,
    contentType: format === 'pdf'
      ? 'application/pdf'
      : format === 'docx'
        ? 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
        : 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    payload,
    checksumSha256: checksum(payload),
  };
}

export function exportSnapshot(snapshot: ReportSnapshot, format: ReportExportFormat): ReportExportResult {
  if (format === 'csv') return exportSnapshotAsCsv(snapshot);
  return exportSnapshotPlaceholder(snapshot, format);
}
