import type { ReportDefinition, ReportTypeKey } from './types';

const COMMON_LEDGER_SOURCES = ['accounts', 'funds', 'journals', 'journal_lines'];

export const REPORT_DEFINITIONS: Record<ReportTypeKey, ReportDefinition> = {
  monthly_dashboard: {
    key: 'monthly_dashboard',
    title: 'Monthly Dashboard',
    description: 'Monthly financial health summary for leadership review.',
    requiredDataSources: [...COMMON_LEDGER_SOURCES, 'bank_accounts', 'budget_lines'],
    supportedFilters: ['year', 'month', 'fundId'],
    supportedExportFormats: ['pdf', 'csv'],
    defaultLayout: 'dashboard',
    trusteeExplanation: 'Shows monthly income, expenditure, cash, fund, and budget signals in one place.',
    validationRules: ['drafts_excluded', 'unreconciled_bank_transactions', 'restricted_fund_negative_balance'],
  },
  income_statement: {
    key: 'income_statement',
    title: 'Income Statement',
    description: 'Income and expenditure by account for the selected reporting period.',
    requiredDataSources: COMMON_LEDGER_SOURCES,
    supportedFilters: ['year', 'month', 'fundId', 'basis'],
    supportedExportFormats: ['pdf', 'csv', 'excel'],
    defaultLayout: 'statement',
    trusteeExplanation: 'Explains whether ordinary activities produced a surplus or deficit.',
    validationRules: ['drafts_excluded', 'missing_fund_or_category_mapping'],
  },
  income_expense_summary: {
    key: 'income_expense_summary',
    title: 'Income And Expense Summary',
    description: 'A concise summary of income and expenditure trends.',
    requiredDataSources: COMMON_LEDGER_SOURCES,
    supportedFilters: ['year', 'fundId'],
    supportedExportFormats: ['pdf', 'csv', 'excel'],
    defaultLayout: 'statement',
    trusteeExplanation: 'Summarises money received and spent for non-finance readers.',
    validationRules: ['drafts_excluded', 'missing_fund_or_category_mapping'],
  },
  balance_sheet: {
    key: 'balance_sheet',
    title: 'Balance Sheet',
    description: 'Assets, liabilities, and funds at a point in time.',
    requiredDataSources: COMMON_LEDGER_SOURCES,
    supportedFilters: ['asOfDate', 'fundId', 'basis'],
    supportedExportFormats: ['pdf', 'csv', 'excel'],
    defaultLayout: 'statement',
    trusteeExplanation: 'Shows what the charity owns, owes, and holds in funds.',
    validationRules: ['balance_sheet_balances', 'drafts_excluded', 'restricted_fund_negative_balance'],
  },
  sofa: {
    key: 'sofa',
    title: 'Statement Of Financial Activities',
    description: 'Charity SOFA split by unrestricted, restricted, and designated funds.',
    requiredDataSources: COMMON_LEDGER_SOURCES,
    supportedFilters: ['year', 'basis'],
    supportedExportFormats: ['pdf', 'csv', 'excel', 'docx'],
    defaultLayout: 'statement',
    trusteeExplanation: 'Shows incoming resources and resources expended by fund class.',
    validationRules: ['drafts_excluded', 'missing_prior_year_data', 'missing_notes'],
  },
  cash_flow: {
    key: 'cash_flow',
    title: 'Cash Flow',
    description: 'Opening cash, movements, and closing cash for the period.',
    requiredDataSources: [...COMMON_LEDGER_SOURCES, 'bank_accounts'],
    supportedFilters: ['year', 'month', 'fundId'],
    supportedExportFormats: ['pdf', 'csv', 'excel'],
    defaultLayout: 'statement',
    trusteeExplanation: 'Explains how cash changed during the period.',
    validationRules: ['unreconciled_bank_transactions', 'drafts_excluded'],
  },
  trial_balance: {
    key: 'trial_balance',
    title: 'Trial Balance',
    description: 'Debit and credit totals by account.',
    requiredDataSources: ['accounts', 'journals', 'journal_lines'],
    supportedFilters: ['asOfDate', 'fundId'],
    supportedExportFormats: ['pdf', 'csv', 'excel'],
    defaultLayout: 'table',
    trusteeExplanation: 'Confirms the ledger balances before producing statutory-style reports.',
    validationRules: ['trial_balance_balances', 'drafts_excluded'],
  },
  budget_vs_actual: {
    key: 'budget_vs_actual',
    title: 'Budget Vs Actual',
    description: 'Budget, actual, and variance by account and month.',
    requiredDataSources: [...COMMON_LEDGER_SOURCES, 'budgets', 'budget_lines'],
    supportedFilters: ['year', 'budgetId', 'fundId'],
    supportedExportFormats: ['pdf', 'csv', 'excel'],
    defaultLayout: 'table',
    trusteeExplanation: 'Highlights where spending or income differs from plan.',
    validationRules: ['drafts_excluded', 'missing_fund_or_category_mapping'],
  },
  fund_movements: {
    key: 'fund_movements',
    title: 'Fund Movements',
    description: 'Opening, income, expenditure, movement, and closing balance by fund.',
    requiredDataSources: COMMON_LEDGER_SOURCES,
    supportedFilters: ['year', 'month'],
    supportedExportFormats: ['pdf', 'csv', 'excel'],
    defaultLayout: 'statement',
    trusteeExplanation: 'Shows how each fund changed and whether restrictions remain healthy.',
    validationRules: ['restricted_fund_negative_balance', 'drafts_excluded'],
  },
  bank_reconciliation_summary: {
    key: 'bank_reconciliation_summary',
    title: 'Bank Reconciliation Summary',
    description: 'Bank statement balances compared with ledger balances.',
    requiredDataSources: ['bank_accounts', 'bank_lines', 'journals', 'journal_lines'],
    supportedFilters: ['asOfDate'],
    supportedExportFormats: ['pdf', 'csv', 'excel'],
    defaultLayout: 'table',
    trusteeExplanation: 'Shows whether bank balances agree to the accounting ledger.',
    validationRules: ['unreconciled_bank_transactions'],
  },
  gift_aid_summary: {
    key: 'gift_aid_summary',
    title: 'Gift Aid Summary',
    description: 'Gift Aid claim, declaration, and outstanding reclaim summary.',
    requiredDataSources: ['donations', 'donors', 'gift_aid_claim_batches'],
    supportedFilters: ['year'],
    supportedExportFormats: ['pdf', 'csv'],
    defaultLayout: 'snapshot',
    trusteeExplanation: 'Explains tax reclaim status and risks around missing declarations.',
    validationRules: ['missing_evidence_or_declarations'],
  },
  lettings: {
    key: 'lettings',
    title: 'Lettings Income',
    description: 'Lettings income and occupancy-style reporting.',
    requiredDataSources: ['lettings_bookings', 'lettings_hirers', 'journals', 'journal_lines'],
    supportedFilters: ['year', 'month'],
    supportedExportFormats: ['pdf', 'csv', 'excel'],
    defaultLayout: 'table',
    trusteeExplanation: 'Shows income from hall or room hire activity.',
    validationRules: ['drafts_excluded', 'missing_fund_or_category_mapping'],
  },
  forecast: {
    key: 'forecast',
    title: 'Forecast Year-End Projection',
    description: 'Projected year-end results using budget and actual trends.',
    requiredDataSources: [...COMMON_LEDGER_SOURCES, 'budget_lines'],
    supportedFilters: ['year', 'month', 'fundId'],
    supportedExportFormats: ['pdf', 'csv', 'excel'],
    defaultLayout: 'snapshot',
    trusteeExplanation: 'Estimates year-end outturn and highlights risk.',
    validationRules: ['missing_prior_year_data', 'drafts_excluded'],
  },
  cash_position: {
    key: 'cash_position',
    title: 'Cash Position',
    description: 'Cash balances by bank account compared with ledger.',
    requiredDataSources: ['bank_accounts', 'bank_lines', 'journals', 'journal_lines'],
    supportedFilters: ['asOfDate'],
    supportedExportFormats: ['pdf', 'csv', 'excel'],
    defaultLayout: 'snapshot',
    trusteeExplanation: 'Shows available cash and differences needing reconciliation.',
    validationRules: ['unreconciled_bank_transactions'],
  },
  supplier_spend: {
    key: 'supplier_spend',
    title: 'Supplier Spend',
    description: 'Spend by supplier for the selected year.',
    requiredDataSources: ['suppliers', 'bills', 'journals', 'journal_lines'],
    supportedFilters: ['year'],
    supportedExportFormats: ['pdf', 'csv', 'excel'],
    defaultLayout: 'table',
    trusteeExplanation: 'Shows major supplier spend and concentration risk.',
    validationRules: ['drafts_excluded', 'missing_evidence_or_declarations'],
  },
  payroll_summary: {
    key: 'payroll_summary',
    title: 'Payroll Summary',
    description: 'Payroll totals, lifecycle status, and staff cost overview.',
    requiredDataSources: ['payroll_runs', 'payroll_lines', 'employees'],
    supportedFilters: ['year', 'month', 'fundId'],
    supportedExportFormats: ['pdf', 'csv', 'excel', 'docx'],
    defaultLayout: 'table',
    trusteeExplanation: 'Summarises payroll costs and controls for treasurer and trustee review.',
    validationRules: ['drafts_excluded'],
  },
  payroll_employer_costs: {
    key: 'payroll_employer_costs',
    title: 'Employer Cost Report',
    description: 'Gross pay, employer NIC, employer pension, and total employer cost.',
    requiredDataSources: ['payroll_runs', 'payroll_lines', 'funds'],
    supportedFilters: ['year', 'month', 'fundId'],
    supportedExportFormats: ['pdf', 'csv', 'excel'],
    defaultLayout: 'table',
    trusteeExplanation: 'Shows the full cost of employing staff, not just net wage payments.',
    validationRules: ['drafts_excluded'],
  },
  payroll_by_fund_ministry: {
    key: 'payroll_by_fund_ministry',
    title: 'Payroll By Fund And Ministry',
    description: 'Payroll costs grouped by fund, department, or ministry allocation.',
    requiredDataSources: ['payroll_lines', 'funds', 'employees'],
    supportedFilters: ['year', 'month', 'fundId'],
    supportedExportFormats: ['pdf', 'csv', 'excel'],
    defaultLayout: 'table',
    trusteeExplanation: 'Explains where payroll cost is carried across funds and ministries.',
    validationRules: ['missing_fund_or_category_mapping'],
  },
  payroll_pension_contributions: {
    key: 'payroll_pension_contributions',
    title: 'Pension Contribution Report',
    description: 'Employee and employer pension contributions and pension payable.',
    requiredDataSources: ['payroll_runs', 'payroll_lines', 'payroll_liability_payments'],
    supportedFilters: ['year', 'month'],
    supportedExportFormats: ['pdf', 'csv', 'excel'],
    defaultLayout: 'table',
    trusteeExplanation: 'Shows pension contributions due and paid to the provider.',
    validationRules: ['drafts_excluded'],
  },
  payroll_paye_nic_liability: {
    key: 'payroll_paye_nic_liability',
    title: 'PAYE/NIC Liability Report',
    description: 'PAYE, employee NIC, employer NIC, and HMRC payment status.',
    requiredDataSources: ['payroll_runs', 'payroll_liability_payments'],
    supportedFilters: ['year', 'month'],
    supportedExportFormats: ['pdf', 'csv', 'excel'],
    defaultLayout: 'table',
    trusteeExplanation: 'Shows payroll liabilities owed to HMRC and settlement status.',
    validationRules: ['drafts_excluded'],
  },
  payroll_vs_budget: {
    key: 'payroll_vs_budget',
    title: 'Payroll Vs Budget',
    description: 'Payroll employer cost compared with available budget lines.',
    requiredDataSources: ['payroll_lines', 'budget_lines', 'funds'],
    supportedFilters: ['year', 'month', 'fundId', 'budgetId'],
    supportedExportFormats: ['pdf', 'csv', 'excel'],
    defaultLayout: 'table',
    trusteeExplanation: 'Highlights payroll cost pressure against plan.',
    validationRules: ['missing_fund_or_category_mapping'],
  },
  trustee_snapshot: {
    key: 'trustee_snapshot',
    title: 'Trustee Snapshot',
    description: 'High-level finance snapshot for trustees.',
    requiredDataSources: [...COMMON_LEDGER_SOURCES, 'bank_accounts', 'budget_lines'],
    supportedFilters: ['asOfDate'],
    supportedExportFormats: ['pdf', 'docx'],
    defaultLayout: 'snapshot',
    trusteeExplanation: 'Provides trustees with the key finance signals and actions.',
    validationRules: ['restricted_fund_negative_balance', 'unreconciled_bank_transactions'],
  },
  leadership_snapshot: {
    key: 'leadership_snapshot',
    title: 'Leadership Snapshot',
    description: 'Plain-English finance summary for operational leaders.',
    requiredDataSources: [...COMMON_LEDGER_SOURCES, 'bank_accounts'],
    supportedFilters: ['asOfDate'],
    supportedExportFormats: ['pdf', 'docx'],
    defaultLayout: 'snapshot',
    trusteeExplanation: 'Explains practical finance actions for leaders.',
    validationRules: ['unreconciled_bank_transactions', 'drafts_excluded'],
  },
  quarterly: {
    key: 'quarterly',
    title: 'Quarterly Report',
    description: 'Quarterly income, expenditure, surplus, and fund balance summary.',
    requiredDataSources: COMMON_LEDGER_SOURCES,
    supportedFilters: ['year', 'quarter'],
    supportedExportFormats: ['pdf', 'csv', 'excel', 'docx'],
    defaultLayout: 'pack',
    trusteeExplanation: 'Summarises quarterly movement for committee review.',
    validationRules: ['drafts_excluded', 'restricted_fund_negative_balance'],
  },
  annual: {
    key: 'annual',
    title: 'Annual Report',
    description: 'Annual accounts-style pack with statements and appendices.',
    requiredDataSources: [...COMMON_LEDGER_SOURCES, 'budget_lines', 'bank_accounts'],
    supportedFilters: ['year', 'basis'],
    supportedExportFormats: ['pdf', 'excel', 'docx'],
    defaultLayout: 'pack',
    trusteeExplanation: 'Pulls together annual financial statements and supporting schedules.',
    validationRules: ['trial_balance_balances', 'balance_sheet_balances', 'missing_prior_year_data', 'missing_notes'],
  },
  agm: {
    key: 'agm',
    title: 'AGM Pack',
    description: 'AGM-ready report pack for members and trustees.',
    requiredDataSources: [...COMMON_LEDGER_SOURCES, 'budget_lines'],
    supportedFilters: ['year', 'basis'],
    supportedExportFormats: ['pdf', 'excel', 'docx'],
    defaultLayout: 'pack',
    trusteeExplanation: 'Explains annual financial performance in a member-friendly format.',
    validationRules: ['balance_sheet_balances', 'missing_prior_year_data', 'missing_notes'],
  },
  export_pack: {
    key: 'export_pack',
    title: 'Export Pack',
    description: 'Combined export bundle for accounting review.',
    requiredDataSources: [...COMMON_LEDGER_SOURCES, 'bank_accounts', 'donations', 'bills'],
    supportedFilters: ['year', 'startDate', 'endDate'],
    supportedExportFormats: ['pdf', 'csv', 'excel', 'docx'],
    defaultLayout: 'pack',
    trusteeExplanation: 'Packages source schedules and reports for review or handover.',
    validationRules: ['drafts_excluded', 'unreconciled_bank_transactions', 'missing_evidence_or_declarations'],
  },
};

export const REPORT_TYPE_KEYS = Object.keys(REPORT_DEFINITIONS) as ReportTypeKey[];

export function getReportDefinition(reportType: ReportTypeKey): ReportDefinition {
  return REPORT_DEFINITIONS[reportType];
}
