import type { YearEndCloseStepDefinition, YearEndCloseStepKey } from './types';

export const YEAR_END_CLOSE_STEPS: YearEndCloseStepDefinition[] = [
  {
    stepKey: 'confirm-financial-year-dates',
    stepNumber: 1,
    title: 'Confirm financial year dates',
    description: 'Confirm the reporting year start and end dates and link them to a financial period.',
    dependencies: [],
    validationSource: 'periods',
    recommendedAction: 'Check the financial period and confirm the year being closed.',
    canWaive: false,
  },
  {
    stepKey: 'confirm-accounting-basis',
    stepNumber: 2,
    title: 'Confirm accounting basis',
    description: 'Confirm whether the accounts are prepared on a cash or accruals basis.',
    dependencies: ['confirm-financial-year-dates'],
    validationSource: 'basis',
    recommendedAction: 'Select the accounting basis before generating annual accounts.',
    canWaive: false,
  },
  {
    stepKey: 'reconcile-bank-accounts',
    stepNumber: 3,
    title: 'Reconcile all bank accounts',
    description: 'All active bank accounts should be reconciled to the financial year end date.',
    dependencies: ['confirm-financial-year-dates'],
    validationSource: 'bank_reconciliation',
    recommendedAction: 'Complete bank reconciliation for every active bank account.',
    canWaive: false,
  },
  {
    stepKey: 'review-unreconciled-transactions',
    stepNumber: 4,
    title: 'Review unreconciled transactions',
    description: 'Review unreconciled bank transactions and explain any items left open.',
    dependencies: ['reconcile-bank-accounts'],
    validationSource: 'bank_transactions',
    recommendedAction: 'Match, allocate, or explain outstanding bank transactions.',
    canWaive: true,
  },
  {
    stepKey: 'review-unposted-drafts',
    stepNumber: 5,
    title: 'Review unposted drafts',
    description: 'Review draft journals, bills, payroll runs, portal submissions, and manual transactions.',
    dependencies: ['confirm-accounting-basis'],
    validationSource: 'drafts',
    recommendedAction: 'Post, approve, reject, or archive all year-end draft items.',
    canWaive: true,
  },
  {
    stepKey: 'review-income-register',
    stepNumber: 6,
    title: 'Review income register',
    description: 'Review giving, donations, lettings income, grants, and other income classifications.',
    dependencies: ['review-unposted-drafts'],
    validationSource: 'income_register',
    recommendedAction: 'Confirm income categories, funds, and supporting records.',
    canWaive: true,
  },
  {
    stepKey: 'review-expense-register',
    stepNumber: 7,
    title: 'Review expense register',
    description: 'Review supplier, payroll, ministry, running cost, and uncategorised expense records.',
    dependencies: ['review-unposted-drafts'],
    validationSource: 'expense_register',
    recommendedAction: 'Confirm expense categories, suppliers, funds, and evidence.',
    canWaive: true,
  },
  {
    stepKey: 'review-restricted-funds',
    stepNumber: 8,
    title: 'Review restricted funds',
    description: 'Check restricted fund balances, movements, and purposes.',
    dependencies: ['review-income-register', 'review-expense-register'],
    validationSource: 'funds',
    recommendedAction: 'Investigate negative restricted funds and confirm fund notes.',
    canWaive: true,
  },
  {
    stepKey: 'review-fund-transfers',
    stepNumber: 9,
    title: 'Review fund transfers',
    description: 'Review transfers between unrestricted, designated, and restricted funds.',
    dependencies: ['review-restricted-funds'],
    validationSource: 'fund_transfers',
    recommendedAction: 'Confirm transfer approval and narrative for material movements.',
    canWaive: true,
  },
  {
    stepKey: 'review-gift-aid-records',
    stepNumber: 10,
    title: 'Review Gift Aid records',
    description: 'Review Gift Aid declarations, claims, exclusions, and outstanding reclaim amounts.',
    dependencies: ['review-income-register'],
    validationSource: 'gift_aid',
    recommendedAction: 'Resolve missing declarations and reconcile claim status.',
    canWaive: true,
  },
  {
    stepKey: 'review-payroll-records',
    stepNumber: 11,
    title: 'Review payroll records',
    description: 'Review payroll runs, tax, pensions, and staff cost annual accounts notes.',
    dependencies: ['review-expense-register'],
    validationSource: 'payroll',
    recommendedAction: 'Confirm payroll runs are approved and payroll notes are complete.',
    canWaive: true,
  },
  {
    stepKey: 'review-debtors-creditors',
    stepNumber: 12,
    title: 'Review debtors/creditors',
    description: 'Review receivables, payables, accruals, prepayments, and deferred income.',
    dependencies: ['review-income-register', 'review-expense-register'],
    validationSource: 'balance_sheet_notes',
    recommendedAction: 'Confirm accruals-basis debtors and creditors schedules.',
    canWaive: true,
  },
  {
    stepKey: 'review-fixed-assets',
    stepNumber: 13,
    title: 'Review fixed assets',
    description: 'Review fixed asset additions, disposals, depreciation, and supporting evidence.',
    dependencies: ['review-expense-register'],
    validationSource: 'balance_sheet_notes',
    recommendedAction: 'Confirm fixed asset register and annual accounts asset notes.',
    canWaive: true,
  },
  {
    stepKey: 'review-loans-liabilities',
    stepNumber: 14,
    title: 'Review loans/liabilities',
    description: 'Review loans, long-term liabilities, short-term liabilities, and repayments.',
    dependencies: ['review-debtors-creditors'],
    validationSource: 'balance_sheet_notes',
    recommendedAction: 'Confirm liability balances agree to statements and notes.',
    canWaive: true,
  },
  {
    stepKey: 'generate-trial-balance',
    stepNumber: 15,
    title: 'Generate trial balance',
    description: 'Generate and review the year-end trial balance.',
    dependencies: ['review-fund-transfers', 'review-gift-aid-records', 'review-payroll-records'],
    validationSource: 'trial_balance',
    recommendedAction: 'Generate a balanced trial balance at the period end date.',
    canWaive: false,
  },
  {
    stepKey: 'validate-balance-sheet',
    stepNumber: 16,
    title: 'Validate balance sheet',
    description: 'Validate that net assets, funds, bank reconciliation, and the trial balance agree.',
    dependencies: ['generate-trial-balance', 'review-debtors-creditors', 'review-fixed-assets', 'review-loans-liabilities'],
    validationSource: 'balance_sheet',
    recommendedAction: 'Resolve any balance sheet or bank reconciliation differences.',
    canWaive: false,
  },
  {
    stepKey: 'generate-annual-accounts',
    stepNumber: 17,
    title: 'Generate annual accounts',
    description: 'Generate the annual accounts pack for trustee and examiner review.',
    dependencies: ['validate-balance-sheet'],
    validationSource: 'annual_accounts',
    recommendedAction: 'Generate the annual accounts from the validated year-end data.',
    canWaive: false,
  },
  {
    stepKey: 'trustee-review',
    stepNumber: 18,
    title: 'Trustee review',
    description: 'Submit the accounts and schedules for trustee review.',
    dependencies: ['generate-annual-accounts'],
    validationSource: 'approvals',
    recommendedAction: 'Record trustee review notes and approval outcome.',
    canWaive: false,
  },
  {
    stepKey: 'independent-examination-checklist',
    stepNumber: 19,
    title: 'Independent examination/audit checklist',
    description: 'Prepare examiner evidence, schedules, and review checklist.',
    dependencies: ['generate-annual-accounts'],
    validationSource: 'approvals',
    recommendedAction: 'Attach examiner materials or record why examination is not required.',
    canWaive: true,
  },
  {
    stepKey: 'final-approval',
    stepNumber: 20,
    title: 'Final approval',
    description: 'Record final approval before locking the financial year.',
    dependencies: ['trustee-review', 'independent-examination-checklist'],
    validationSource: 'approvals',
    recommendedAction: 'Capture final approval and trustee meeting reference.',
    canWaive: false,
  },
  {
    stepKey: 'lock-financial-year',
    stepNumber: 21,
    title: 'Lock financial year',
    description: 'Lock the financial period to prevent posting or edits into the closed year.',
    dependencies: ['final-approval'],
    validationSource: 'period_lock',
    recommendedAction: 'Lock the linked financial period after final approval.',
    canWaive: false,
  },
  {
    stepKey: 'export-filing-pack',
    stepNumber: 22,
    title: 'Export filing pack',
    description: 'Generate the filing pack, evidence index, export manifest, and Annual Return Assistant summary.',
    dependencies: ['lock-financial-year'],
    validationSource: 'filing_pack',
    recommendedAction: 'Export the annual accounts, schedules, evidence, and annual return data pack.',
    canWaive: false,
  },
  {
    stepKey: 'mark-submitted',
    stepNumber: 23,
    title: 'Mark submitted',
    description: 'Record when the filing pack has been submitted outside Church Ledger.',
    dependencies: ['export-filing-pack'],
    validationSource: 'submission',
    recommendedAction: 'Enter the submission date, user, and optional Charity Commission reference.',
    canWaive: false,
  },
];

export function getYearEndCloseStepDefinition(stepKey: YearEndCloseStepKey) {
  return YEAR_END_CLOSE_STEPS.find((step) => step.stepKey === stepKey) ?? null;
}

export function getDependentYearEndCloseSteps(stepKey: YearEndCloseStepKey) {
  return YEAR_END_CLOSE_STEPS.filter((step) => step.dependencies.includes(stepKey));
}
