import type { ComponentType, ReactNode } from 'react';
import {
  Document,
  Page,
  StyleSheet,
  Text,
  View,
  renderToBuffer,
} from '@react-pdf/renderer';
import type {
  GiftAidGasdsScheduleWorkbookRow,
  GiftAidScheduleRow,
  GiftAidScheduleValidationSummary,
} from './export-schedule';

const PdfDocument = Document as unknown as ComponentType<{
  title?: string;
  children: ReactNode;
}>;
const PdfPage = Page as unknown as ComponentType<{
  size?: string;
  style?: unknown;
  children: ReactNode;
}>;
const PdfText = Text as unknown as ComponentType<{
  style?: unknown;
  children?: ReactNode;
}>;
const PdfView = View as unknown as ComponentType<{
  style?: unknown;
  children: ReactNode;
}>;

const styles = StyleSheet.create({
  page: {
    padding: 32,
    fontSize: 9,
    fontFamily: 'Helvetica',
    color: '#111827',
  },
  title: {
    fontSize: 18,
    fontWeight: 700,
    marginBottom: 4,
  },
  subtitle: {
    color: '#4b5563',
    marginBottom: 16,
  },
  summary: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 16,
  },
  summaryBox: {
    border: '1 solid #d1d5db',
    borderRadius: 4,
    padding: 8,
    flexGrow: 1,
  },
  summaryLabel: {
    color: '#6b7280',
    fontSize: 8,
    marginBottom: 2,
  },
  summaryValue: {
    fontSize: 12,
    fontWeight: 700,
  },
  row: {
    flexDirection: 'row',
    borderBottom: '1 solid #e5e7eb',
    paddingVertical: 4,
  },
  header: {
    backgroundColor: '#f3f4f6',
    fontWeight: 700,
  },
  cell: {
    paddingHorizontal: 3,
  },
  donor: { width: '29%' },
  postcode: { width: '13%' },
  date: { width: '14%' },
  amount: { width: '12%' },
  sectionTitle: {
    marginTop: 14,
    marginBottom: 6,
    fontSize: 11,
    fontWeight: 700,
  },
  gasdsBatch: { width: '22%' },
  gasdsAmount: { width: '15%' },
  notice: {
    marginTop: 14,
    color: '#6b7280',
    fontSize: 8,
  },
});

function pounds(pence: number) {
  return `£${(pence / 100).toFixed(2)}`;
}

function GiftAidSchedulePdf({
  rows,
  gasdsRows,
  summary,
  batchLabel,
}: {
  rows: GiftAidScheduleRow[];
  gasdsRows?: GiftAidGasdsScheduleWorkbookRow[];
  summary: GiftAidScheduleValidationSummary;
  batchLabel: string;
}) {
  const gasdsPreview = gasdsRows?.slice(0, 20) ?? [];
  return (
    <PdfDocument title="Gift Aid schedule review">
      <PdfPage size="A4" style={styles.page}>
        <PdfText style={styles.title}>Gift Aid schedule review copy</PdfText>
        <PdfText style={styles.subtitle}>
          Internal review copy for {batchLabel}. The spreadsheet export is the HMRC submission artefact.
        </PdfText>

        <PdfView style={styles.summary}>
          <PdfView style={styles.summaryBox}>
            <PdfText style={styles.summaryLabel}>HMRC donor rows</PdfText>
            <PdfText style={styles.summaryValue}>{String(summary.hmrcScheduleRowCount)}</PdfText>
          </PdfView>
          <PdfView style={styles.summaryBox}>
            <PdfText style={styles.summaryLabel}>GASDS batches</PdfText>
            <PdfText style={styles.summaryValue}>{String(summary.gasdsSmallDonationBatchRowCount)}</PdfText>
          </PdfView>
          <PdfView style={styles.summaryBox}>
            <PdfText style={styles.summaryLabel}>Gift Aid total</PdfText>
            <PdfText style={styles.summaryValue}>{pounds(summary.totalGiftAidAmountPence)}</PdfText>
          </PdfView>
          <PdfView style={styles.summaryBox}>
            <PdfText style={styles.summaryLabel}>Donations total</PdfText>
            <PdfText style={styles.summaryValue}>{pounds(summary.totalDonationAmountPence)}</PdfText>
          </PdfView>
        </PdfView>

        <PdfView style={[styles.row, styles.header]}>
          <PdfText style={[styles.cell, styles.donor]}>Donor</PdfText>
          <PdfText style={[styles.cell, styles.postcode]}>Postcode</PdfText>
          <PdfText style={[styles.cell, styles.date]}>Date</PdfText>
          <PdfText style={[styles.cell, styles.amount]}>Amount</PdfText>
        </PdfView>
        {rows.slice(0, 36).map((row, index) => (
          <PdfView key={`${row.lastName}-${row.donationDate}-${index}`} style={styles.row}>
            <PdfText style={[styles.cell, styles.donor]}>
              {[row.title, row.firstNameOrInitial, row.lastName].filter(Boolean).join(' ')}
            </PdfText>
            <PdfText style={[styles.cell, styles.postcode]}>{row.postcode}</PdfText>
            <PdfText style={[styles.cell, styles.date]}>{row.donationDate}</PdfText>
            <PdfText style={[styles.cell, styles.amount]}>£{row.amount}</PdfText>
          </PdfView>
        ))}

        <PdfText style={styles.notice}>
          {rows.length > 36 ? `Showing first 36 of ${rows.length} donor schedule rows. ` : ''}
          Generated by Church Ledger for internal review/archive.
        </PdfText>

        {gasdsPreview.length > 0 ? (
          <>
            <PdfText style={styles.sectionTitle}>GASDS — small donations ({gasdsRows?.length ?? 0})</PdfText>
            <PdfView style={[styles.row, styles.header]}>
              <PdfText style={[styles.cell, styles.gasdsBatch]}>Batch</PdfText>
              <PdfText style={[styles.cell, styles.date]}>Date</PdfText>
              <PdfText style={[styles.cell, styles.donor]}>Service / event</PdfText>
              <PdfText style={[styles.cell, styles.amount]}>Eligible</PdfText>
              <PdfText style={[styles.cell, styles.amount]}>Gift Aid</PdfText>
            </PdfView>
            {gasdsPreview.map((row, index) => (
              <PdfView key={`${row.batchReference}-${index}`} style={styles.row}>
                <PdfText style={[styles.cell, styles.gasdsBatch]}>{row.batchReference}</PdfText>
                <PdfText style={[styles.cell, styles.date]}>{row.collectionDate}</PdfText>
                <PdfText style={[styles.cell, styles.donor]}>{row.serviceOrEvent}</PdfText>
                <PdfText style={[styles.cell, styles.amount]}>£{row.eligiblePounds}</PdfText>
                <PdfText style={[styles.cell, styles.amount]}>£{row.giftAidPounds}</PdfText>
              </PdfView>
            ))}
          </>
        ) : null}
      </PdfPage>
    </PdfDocument>
  );
}

export async function renderGiftAidScheduleReviewPdf(params: {
  rows: GiftAidScheduleRow[];
  gasdsRows?: GiftAidGasdsScheduleWorkbookRow[];
  summary: GiftAidScheduleValidationSummary;
  batchLabel: string;
}) {
  return renderToBuffer(
    <GiftAidSchedulePdf
      rows={params.rows}
      gasdsRows={params.gasdsRows}
      summary={params.summary}
      batchLabel={params.batchLabel}
    />
  );
}
