import ExcelJS from 'exceljs';
import { checksumSha256, safeFilePart } from './hash';
import { withStandardSections } from './templates';
import type { DocumentModel, DocumentRenderResult } from './types';

function safeSheetName(value: string, fallback: string) {
  const safe = value.replace(/[\\/*?:[\]]/g, ' ').slice(0, 31).trim();
  return safe || fallback;
}

export async function renderDocumentExcel(model: DocumentModel): Promise<DocumentRenderResult> {
  const prepared = withStandardSections(model);
  const workbook = new ExcelJS.Workbook();
  workbook.creator = prepared.metadata.generatedBy;
  workbook.created = new Date(prepared.metadata.generatedAt);
  workbook.modified = new Date(prepared.metadata.generatedAt);

  const summary = workbook.addWorksheet('Summary');
  summary.columns = [
    { header: 'Field', key: 'field', width: 28 },
    { header: 'Value', key: 'value', width: 60 },
  ];
  summary.addRows([
    { field: 'Organisation', value: prepared.metadata.organisationName },
    { field: 'Charity number', value: prepared.metadata.charityNumber ?? 'Not provided' },
    { field: 'Report title', value: prepared.metadata.reportTitle },
    { field: 'Period', value: prepared.metadata.periodLabel },
    { field: 'Status', value: prepared.metadata.status },
    { field: 'Version', value: prepared.metadata.version },
    { field: 'Generated at', value: prepared.metadata.generatedAt },
    { field: 'Generated by', value: prepared.metadata.generatedBy },
  ]);
  summary.views = [{ state: 'frozen', ySplit: 1 }];
  summary.getRow(1).font = { bold: true };

  for (const [sectionIndex, section] of prepared.sections.entries()) {
    const tables = section.tables ?? [];
    if (tables.length === 0) {
      const sheet = workbook.addWorksheet(safeSheetName(section.title, `Section ${sectionIndex + 1}`));
      sheet.addRow([section.title]);
      sheet.addRows((section.body ?? []).map((line) => [line]));
      continue;
    }

    for (const [tableIndex, table] of tables.entries()) {
      const sheet = workbook.addWorksheet(safeSheetName(table.title, `Table ${sectionIndex + 1}-${tableIndex + 1}`));
      sheet.addRow(table.headers);
      sheet.addRows(table.rows);
      sheet.views = [{ state: 'frozen', ySplit: 1 }];
      sheet.getRow(1).font = { bold: true };
      sheet.columns.forEach((column) => {
        column.width = Math.max(14, String(column.header ?? '').length + 4);
        column.numFmt = '#,##0.00;[Red]-#,##0.00';
      });
      for (const formula of table.formulas ?? []) {
        sheet.getCell(formula.cell).value = { formula: formula.formula, result: formula.result };
      }
    }
  }

  const buffer = await workbook.xlsx.writeBuffer();
  const payload = buffer instanceof Uint8Array ? buffer : new Uint8Array(buffer);
  return {
    format: 'excel',
    fileName: `${safeFilePart(prepared.metadata.reportTitle)}-v${prepared.metadata.version}.xlsx`,
    contentType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    payload,
    checksumSha256: checksumSha256(payload),
    metadata: prepared.metadata,
    validationSnapshot: prepared.validationSnapshot,
  };
}
